- name: Create folder to mount data disk for SQL
  file: 
    path: /sql
    state: directory
    owner: mssql
    group: mssql
    mode: 0755

- name: Run create SQL disk role
  include_role:
    name: sqldisk

- name: Create SQL data folder
  file: 
    path: /sql/sqldata
    state: directory
    owner: mssql
    group: mssql
    mode: 0755

- name: Create SQL log folder
  file: 
    path: /sql/sqllog
    state: directory
    owner: mssql
    group: mssql
    mode: 0755

- name: Create SQL log folder
  file: 
    path: /sql/sqlbackup
    state: directory
    owner: mssql
    group: mssql
    mode: 0755

- name: set memory.memorylimitmb
  command: /opt/mssql/bin/mssql-conf set memory.memorylimitmb {{ mssql_memory_memorylimitmb }}
  become: yes
  notify: restart_mssql

- name: enable sql server agent
  command: /opt/mssql/bin/mssql-conf set sqlagent.enabled true
  become: yes
  notify: restart_mssql

- name: change default data file path
  command: /opt/mssql/bin/mssql-conf set filelocation.defaultdatadir /sql/sqldata
  become: yes
  notify: restart_mssql

- name: change default log file path
  command: /opt/mssql/bin/mssql-conf set filelocation.defaultlogdir /sql/sqllog
  become: yes
  notify: restart_mssql

- name: change default log file path
  command: /opt/mssql/bin/mssql-conf set filelocation.defaultbackupdir /sql/sqlbackup
  become: yes
  notify: restart_mssql

  