---

- name: stop the mssql service if running first
  service:
    name: mssql-server
    state: stopped

# unfortunately there is no way (I know of) to be idempotent
- name: setup
  command: /opt/mssql/bin/mssql-conf -n setup accept-eula
  environment:
    MSSQL_SA_PASSWORD: "{{ mssql_sa_password }}"
    MSSQL_PID: "{{ mssql_pid }}"
  become: yes
  ignore_errors: yes

- name: set memory.memorylimitmb
  command: /opt/mssql/bin/mssql-conf set memory.memorylimitmb {{ mssql_memory_memorylimitmb }}
  become: yes
  notify: restart_mssql

- name: enable sql server agent
  command: /opt/mssql/bin/mssql-conf set sqlagent.enabled true
  become: yes
  notify: restart_mssql