---

# unfortunately there is no way (I know of) to be idempotent
- name: setup
  command: /opt/mssql/bin/mssql-conf -n setup accept-eula
  environment:
    MSSQL_SA_PASSWORD: "{{ mssql_sa_password }}"
    MSSQL_PID: "{{ mssql_pid }}"
  become: yes
  ignore_errors: yes

- name: ufw allow rule
  ufw:
    rule: allow
    port: 1433
    proto: tcp
    state: reloaded
  become: yes

- name: set memory.memorylimitmb
  command: /opt/mssql/bin/mssql-conf set memory.memorylimitmb {{ mssql_memory_memorylimitmb }}
  become: yes
  notify: restart_mssql
