---

# unfortunately there is no way (I know of) to be idempotent
- name: setup
  command: /opt/mssql/bin/mssql-conf -n setup accept-eula
  environment:
    MSSQL_SA_PASSWORD: "{{ mssql_sa_password }}"
    MSSQL_PID: "{{ mssql_pid }}"
  become: yes
  ignore_errors: yes
